service: lx-backend-challenge

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  region: ap-southeast-2

functions:
  handler:
    handler: handler/main.main
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: "*"
            allowCredentials: false
